// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9OV5jcFkxjpNh_my6IxmyXNm3cxZsn_8',
    appId: '1:983750664572:web:2487358ae86d3e773c04f9',
    messagingSenderId: '983750664572',
    projectId: 'karta-6fc8b',
    authDomain: 'karta-6fc8b.firebaseapp.com',
    storageBucket: 'karta-6fc8b.firebasestorage.app',
    measurementId: 'G-DW6NK64PGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM4z6bG25sUMQMbRDmcxTEAPvaaGcCHjo',
    appId: '1:983750664572:android:cf013c768f87e0ba3c04f9',
    messagingSenderId: '983750664572',
    projectId: 'karta-6fc8b',
    storageBucket: 'karta-6fc8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd2Dju1PVEg0SUVug_AHWd-5qcgx2wfoE',
    appId: '1:983750664572:ios:24e5f3470fb832e03c04f9',
    messagingSenderId: '983750664572',
    projectId: 'karta-6fc8b',
    storageBucket: 'karta-6fc8b.firebasestorage.app',
    iosBundleId: 'com.example.kartaApp',
  );
}
